@startuml Mascota

package Sentimiento{
class Sentimiento
class Felicidad
class Tristeza
class Cansancio
class Aburrimiento
}
package Alimento{
class Alimento
class Comida
class Agua
}
package Juguete{
class Juguete
class Pelota
class Carro
}
package Necesidad{
class Necesidad
class Hambre
class Sed
class Bañar
class Jugar
class Limpieza
}
package Habitacion{
class Habitacion
class Baño
class Color
class Luz
}

class Mascota{
-habitacion:Habitacion
+Comer(Alimento)
+Usar(Ropa)
+Consumir(Energia)
}
class Energia
class Dueño
class Ropa

Comida--|>Alimento
Mascota"1" o-- "1"Alimento
Pelota--|>Juguete
Mascota"1" o-- "1..*"Juguete
Agua--|>Alimento
Felicidad--|>Sentimiento
Tristeza--|>Sentimiento
Sentimiento"1" --* "1"Mascota
Mascota"1" o-- "*"Energia
Mascota*-- Dueño
Carro--|>Juguete
Habitacion--*Mascota
Luz--*Habitacion
Aburrimiento--|>Sentimiento
Habitacion*--Color
Necesidad<|--Hambre
Mascota*--Necesidad
Necesidad<|--Sed
Bañar--|>Necesidad
Jugar--|>Necesidad
Mascota o-- Ropa
Habitacion*--Baño
Limpieza--|>Necesidad
Cansancio--|>Sentimiento